"""Add agent_capabilities table

Revision ID: b58060cb04cc
Revises: 
Create Date: 2025-07-27 12:54:50.067290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'b58060cb04cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add metadata column to agent_action_logs
    with op.batch_alter_table('agent_action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=True))
        
        # Get the current foreign key constraints
        inspector = Inspector.from_engine(op.get_bind())
        fks = inspector.get_foreign_keys('agent_action_logs')
        
        # Drop existing foreign key constraint if it exists
        for fk in fks:
            if fk['referred_table'] == 'agents' and 'agent_id' in fk['constrained_columns']:
                if fk.get('name'):
                    batch_op.drop_constraint(fk['name'], type_='foreignkey')
        
        # Create new foreign key with CASCADE on delete
        batch_op.create_foreign_key('fk_agent_action_logs_agent_id', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('agent_conversations', schema=None) as batch_op:
        # Make title non-nullable
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        
        # Get the current foreign key constraints
        inspector = Inspector.from_engine(op.get_bind())
        fks = inspector.get_foreign_keys('agent_conversations')
        
        # Drop existing foreign key constraint if it exists
        for fk in fks:
            if fk['referred_table'] == 'agents' and 'agent_id' in fk['constrained_columns']:
                if fk.get('name'):
                    batch_op.drop_constraint(fk['name'], type_='foreignkey')
        
        # Create new foreign key with CASCADE on delete
        batch_op.create_foreign_key('fk_agent_conversations_agent_id', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        # Drop the timestamp index if it exists
        inspector = Inspector.from_engine(op.get_bind())
        indexes = [idx['name'] for idx in inspector.get_indexes('agent_messages')]
        if 'ix_agent_messages_timestamp' in indexes:
            batch_op.drop_index('ix_agent_messages_timestamp')
        
        # Get the current foreign key constraints
        fks = inspector.get_foreign_keys('agent_messages')
        
        # Drop existing foreign key constraint if it exists
        for fk in fks:
            if fk['referred_table'] == 'agent_conversations' and 'conversation_id' in fk['constrained_columns']:
                if fk.get('name'):
                    batch_op.drop_constraint(fk['name'], type_='foreignkey')
        
        # Create new foreign key with CASCADE on delete
        batch_op.create_foreign_key('fk_agent_messages_conversation_id', 'agent_conversations', 
                                  ['conversation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_messages_conversation_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'agent_conversations', ['conversation_id'], ['id'])
        batch_op.create_index('ix_agent_messages_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('agent_conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_conversations_agent_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'agents', ['agent_id'], ['id'])
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('agent_action_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_action_logs_agent_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'agents', ['agent_id'], ['id'])
        batch_op.drop_column('metadata')

    # ### end Alembic commands ###
